project:
  type: website

website:
  title: "Plastic Pollution"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Graphs
        menu:
          - href: global-plastics-production.qmd
            text: Global Plastics Production

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



