project:
  type: website

website:
  title: "Plastic Pollution"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Graphs
        menu:
          - href: global-plastics-production.qmd
            text: Global Plastics Production
          - href: share-of-global-plastic-waste-emitted-to-the-ocean.qmd
            text: Share of Global Plastic Waste Emitted to the Ocean
          - href: share-plastic-fate.qmd
            text: Share Plastic Fate

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



